name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Default Scheme
        id: scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -r 'json' -e 'puts JSON.parse(STDIN.gets)["project"]["targets"][0]')
          echo "SCHEME=$default" >> $GITHUB_ENV
          echo "Using default scheme: $default"

      - name: Build
        run: |
          xcodebuild build-for-testing \
            -scheme "$SCHEME" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14'

      - name: Test
        run: |
          xcodebuild test-without-building \
            -scheme "$SCHEME" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14'
      
