name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and test
        run: |
          xcodebuild -project ThriveCheckAI.xcodeproj \
                     -scheme ThriveCheckAI \
                     -sdk iphonesimulator \
                     -destination 'platform=iOS Simulator,name=iPhone 14' \
                     build test
